experiment:
  seed:           123
  num_epochs:     2000
  batch_size:     1024
  learning_rate:  0.0001
  cuda_index:     3


pde_dataset:
  path_train:     "/media/junseung/47a90e46-3a9d-467c-bbee-066752b68532/GWANGJAE/datasets_kinetic/Boltzmann_2D/biMaxwellian/coeff1.59e-01/res032"
  path_val:       "/media/junseung/47a90e46-3a9d-467c-bbee-066752b68532/GWANGJAE/datasets_kinetic/Boltzmann_2D/biMaxwellian/coeff1.59e-01/res032"
  path_test:     "/media/junseung/47a90e46-3a9d-467c-bbee-066752b68532/GWANGJAE/datasets_kinetic/Boltzmann_2D/biMaxwellian/coeff1.59e-01/res064"
  resolution:     32
  downsample:     1
  num_time_steps: 51


rfno:
  n_modes:            [16,16]
  in_channels:        1
  hidden_channels:    32
  out_channels:       1

  lift_layer:         [128, 128]
  n_layers:           4
  project_layer:      [128, 128]

  activation_name:    "relu"
  activation_kwargs:  {}

  pos_enc:  True

  delta_t:  0.1


##################################################
##################################################
# End of file