experiment:
  batch_size:     4
  test_size:      50


pde_dataset:
  path:           "/ssd/PANGPANG/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_2.npz"
  resolution:     241
  file_index:     2
  downsample:     4


graph:
  radius:         0.1
  # No sampling in the test phase


gno:
  in_channels:      6
  hidden_channels:  32
  out_channels:     1
  edge_channels:    6
  n_layers:         6
  lift_layer:       []
  kernel_layer:     [256, 256]
  project_layer:    []
  activation:       "relu"
  # 0 for the custom model, 1 for the reference model
  gno_index:        1