experiment:
  batch_size:     16
  test_size:      500
  cuda_index:     0


pde_dataset:
  path:           "E:/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_2.npz"
  # path:           "/ssd/PANGPANG/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_2.npz"
  resolution:     241
  file_index:     2
  downsample:     1
  downsample_train: 8


deeponet:
  channels_branch:    [961, 512, 512, 256]
  channels_trunk:     [2, 256, 256, 256]
  activation_name:    "relu"




train_prefix: "202407062346"