experiment:
  num_epochs:     300
  batch_size:     16
  learning_rate:  0.001
  train_size:     100
  val_size:       50
  cuda_index:     0


pde_dataset:
  path:           "E:/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_1.npz"
  # path:           "/ssd/PANGPANG/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_1.npz"
  resolution:     241
  file_index:     1
  downsample:     16


graph:
  radius:         0.1
  sample_size:    -1
  num_sampling:   -1


gno:
  in_channels:      6
  hidden_channels:  32
  out_channels:     1
  edge_channels:    6
  n_layers:         6
  lift_layer:       [64]
  kernel_layer:     [128, 128]
  project_layer:    [64]
  activation:       "relu"