experiment:
  batch_size:     16
  test_size:      500
  cuda_index:     0


pde_dataset:
  path:           "E:/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_2.npz"
  # path:           "/ssd/PANGPANG/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_2.npz"
  resolution:     241
  file_index:     2
  downsample:     1


gt:
  dim_domain:       2
  in_channels:      6
  hidden_channels:  64
  out_channels:     1
  n_layers:         4
  n_heads:          4
  activation_name:  "relu"



train_prefix: "20240729_171418"