experiment:
  num_epochs:     300
  batch_size:     16
  learning_rate:  0.001
  lr_step:        20
  lr_gamma:       0.8
  train_size:     800
  val_size:       200
  cuda_index:     0


pde_dataset:
  path:           "E:/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_1.npz"
  # path:           "/ssd/PANGPANG/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_1.npz"
  resolution:     241
  file_index:     1
  downsample:     8


gt:
  dim_domain:       2
  in_channels:      6
  hidden_channels:  64
  out_channels:     1
  n_layers:         4
  n_heads:          4
  activation_name:  "relu"
