experiment:
  batch_size:     16
  test_size:      500
  cuda_index:     0


pde_dataset:
  path:           "E:/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_2.npz"
  # path:           "/ssd/PANGPANG/PDE_datasets/from_pde_dataset/Darcy flow/Darcy241_2.npz"
  resolution:     241
  file_index:     2
  downsample:     1


fno:
  n_modes:          [12, 12]
  in_channels:      3
  hidden_channels:  32
  out_channels:     1
  lift_layer:       [64]
  n_layers:         4
  project_layer:    [64]
  activation:       "relu"


train_prefix: "20250217_144931"